### PR TITLE
Working on Adding CPM Support to Doxybook

### PR DESCRIPTION
**Pull request by amirmasoudabdol**
Hi Matus,

What do you think of using [CPM](https://github.com/cpm-cmake/CPM.cmake) as the package manager? In my experience it works very well, and most of the time you don't need to do anything extra, or install any other package manager. It's especially nice when you don't have access to `vcpkg`, e.g., some CI environments. 

In this PR, I managed to integrated almost all the dependencies and build the Doxybook2 just by CMake. However, there is a problem. The ArgAgg package is quite old, and does not support CMake very well, and it causes some issues during the build process of the CLI tools which is a bummer since everything else works just fine. 

I'm wondering about your thoughts on this, and whether you see a solution around the ArgAgg (including it as a single header) that can solve this issues. If ArgAgg behaves nicely, then, I think it's nice to have this in the project. The other option is to fix ArgAgg but I don't have my hopes high for that since the project is very inactive and there are some PR and issues handing around for a while in the repo.

Cheers,
Amir.

### CODE REVIEW

**Comment by matusnovak** [comment]
Hi @amirmasoudabdol 

That's an interesting package manager. Never heard of it before. Thank you for bringing that to my attention.

Yes it would be nice to have it. Although, it should be optional. Perhaps wrapping the `CPMAddPackage` in the `CMakeLists.txt` file via `if() / endif()` would be sufficient. I wish not to remove the vcpkg integration, and making PCM optional would be best, so that the user can choose which option to go with.

As for the ArgAgg, I know that it is bit of a pain. I don't mind swapping that with an another library that does the same thing. Do you have any recommendations? Something that is not just C and plays well with C++.

I have enabled the GitHub actions for you. It seems that these changes in this PR made it to error. Just in case, I have just run a build on `master` branch https://github.com/matusnovak/doxybook2/actions/runs/875827684 and runs just fine.

I would suggest to not to use PCM during the existing build. However, you can add another job that builds with PCM instead of vcpkg.

**Comment by amirmasoudabdol** [comment]
I agree. I think it'd be nice to have it as an alternative. I will see how I can continue with this. I think I should adjust the actions too! 🤔 

For the CLI library, I personally use [Boost::ProgramOptions](https://www.boost.org/doc/libs/1_76_0/doc/html/program_options.html) since we are using Boost in our project. But that doesn't make sense here. I looked into this once, and I remember hearing good things about [CLI11](https://github.com/CLIUtils/CLI11). Another option is [cxxopts](https://github.com/jarro2783/cxxopts). Both are rather modern and being actively maintained.

**Comment by amirmasoudabdol** [comment]
I have made some changes for you to see how the `CMakeLists.txt` will look like after dropping the `argagg`.

**Comment by matusnovak** [comment]
Hi @amirmasoudabdol 

Thank you for all of your hard work. I will have a closer look at this later this week. I have been moving into a new place last couple of week and have been busy.

This PR however seems that it may need rebasing. There are couple of commits in here that already exist on the master.

Also, could you either create one PR with all of your changes (preferably in separate commits, as it is now) or three different PRs with unique changes? I see that your change for dropping `argagg` is in all 3 PRs at the same time. It would be much easier for me to go through it if all of the PRs are separate from each other. Or one massive PR, if that is your only option. I will leave the decision to you.

Thanks

**Comment by amirmasoudabdol** [comment]
Hi @matusnovak,

I think I kind of messed up the git stuff of this one. Let me see what can I do! I try to rebase first, and see what do I get. I'm not sure how to separate these into 3 different PRs honestly. I think you can kind of see them in the other two PRs that I made. The `argagg` replacement is quite inclusive, but the other ones are kind of mixed. I kind of had to mix them also since I had to deal with CMake, Vcpkg, and the changes.

Either way, let me rebase first and we see were we get from there.

Cheers,
A.

**Pull request closed without merging**
