### PR TITLE
Prefer linking to entities in groups instead of entities in namespaces

### PR DESCRIPTION
**Pull request by brycelelbach**
Make sure to load basic information from groups first, so that when the same entity appears in both a group and a namespace, the link map points to the group reference not the namespace reference. This mirrors what Doxygen's HTML output does.

For example, one of my classes has a member function with a Doxygen `\see` comment that references a function which is in a group.

In the Doxygen XML, this reference appears as:

````
<simplesect kind="see"><para><ref refid="group__memory__management_1ga6a56463dcea00aaefa0371f80a462f4e" kindref="member">device_new</ref></para>
```

The corresponding `memberdef` for that ref appears in two places in the Doxygen XML output for my project:

* `namespacethrust.xml`
* `group__memory__mangement.xml`

In the Doxygen HTML output for `device_ptr`, the link for `device_new` goes to the group page, not the namespace page. But in Doxybook, it goes to the namespace page, not the group page.

This happens because `namespacethrust.xml` gets loaded first and its `memberdef` for `device_new` gets added to the unordered map of links first.

By loading basic info from all groups first, we ensure that links to an entity will point to a group page if they're in one before a namespace page.

### CODE REVIEW

**Comment by brycelelbach** [comment]
Interesting, this seems to be causing the pages build to choke and seg fault, not sure why. It's been working for our codebase. @matusnovak do you have any better ideas on how I might achieve what I'm looking for here?

**Comment by brycelelbach** [comment]
When I first made this change, I ran into issues with the JSON converter trying to access null parent nodes - it looks like a null check was missing. I'm not sure why this change in particular uncovered it. I manually diffed the output of our project ([Thrust](https://github.com/NVIDIA/thrust)) and the only diffs I saw were links being changed to point to group pages not namespace pages, so I'm pretty sure this change isn't doing anything evil under the hood.

**Comment by matusnovak** [comment]
This makes sense. Just in case I have tested it with some other projects and looks fine.

**Comment by matusnovak** [comment]
In the end, I had to change this. This PR was breaking generation of index pages in their respective folders. I didn't spot it in the beginning.

Instead of changing how entities are assigned to parents, I have changed generation of URLs for the affected entities instead. So that if the entity is marked explicitly to be part of a module/group (i.e. part of the group__abc.xml file), it will be visible on both the group/module page and on the page of its parent (namespace, file, etc.), but the link (from anywhere) to that entity will point to the group/module page.

This way only the URL generation is changed and the parent behavior stays the same.

Example, a function `getVersion()` that belongs to namespace `Engine::` and module `Engine`. Located here: https://matusnovak.github.io/doxybook2/hugo-book/namespaces/namespaceengine/#functions

Also located here:
https://matusnovak.github.io/doxybook2/hugo-book/modules/group__engine/#functions

Clicking on it (or any link that references this function) will redirect the user to the module page, as per your request in this PR.

**Pull request merged**
