### PR TITLE
Full CPM Integration (+ spdlog)

### PR DESCRIPTION
**Pull request by amirmasoudabdol**
This PR basically summarises everything that I had plan.

- It replaces your logging with `spdlog` library
- It fully integrates the CPM for package handling.
- I added the `USE_CPM` flag to the CMake. When used CMake uses the CPM to download all the dependencies and prepares everything. If not, the build goes as before and nothing changes.
- Removed `rang` and replaced it with the `spdlog`
- Removed `argagg` and replaced it with the `cxxopts`

Feel free to ask me about the changes. I understand that this might be a lot of changes and a bit too much for one PR, but I had to do it like this. I can walk you through the changes if necessary! 🙂 Of course, it needs to be tested properly as well, and I think you should take the lead on that. I'm not fully aware of all the functionalities and their expected behaviours.

Cheers,
Amir.

### CODE REVIEW

**Comment by matusnovak** [comment]
Hi @amirmasoudabdol 

Could you check my comment in your previous PR here https://github.com/matusnovak/doxybook2/pull/44#issuecomment-896308451 please?

**Comment by amirmasoudabdol** [comment]
Hi @matusnovak,

I decided to close the old repo, and work on this one. Honestly, I'm not so sure how to split this into smaller PRs without doing everything again! So, what I did was to rebase the branch and it's up-to-date. There were no conflicts, and I think it contains everything. 

For what's happening, I left the #61 open, and in it you can see how I replaced the `argagg`, and that's only dedicated to the `argagg`, so you should be able to see what's happening fully. **But, when you reviewed it, just close it since this PR includes everything.**

For replacing the `Log.h/cpp`, things are a bit more complicated since I had to replace all logging instances, but I think it's quite straightforward. I basically, searched and replaced all instances of your logging with `spdlog`, and made sure that everything works.

For the CMakeLists.txt stuff, everything is included in the `CMakeLists.txt` file, so that's also somewhat isolated. 

Please let me know if I can do anything more! :-) 

Cheers,
Amir.

**Comment by matusnovak** [comment]
Hi @amirmasoudabdol 

Sorry, stuff came up and I will not be available right now. I will have a look at this PR next week.

**Comment by matusnovak** [comment]
@amirmasoudabdol  Awesome work! Thank you. You can close your second PR https://github.com/matusnovak/doxybook2/pull/61 because those changes are already in this one and merged. Thanks again.

**Comment by amirmasoudabdol** [comment]
Nice to see this being merged! 👏🏼

**Pull request merged**
